"use client"

import { useId } from "react"
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts"

import type { RevenueCustomerStatistic } from "@/features/revenue-analytics/types"
import { formatCompactCount } from "@/features/dashboard/utils/format"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/components/ui/chart"

type RevenueCustomerStatisticsChartProps = {
  customerStatistics: RevenueCustomerStatistic[]
}

const chartConfig = {
  returning_customers: {
    label: "Returning Customers",
    color: "var(--primary)",
  },
  new_customers: {
    label: "New Customers",
    color: "rgba(255, 181, 65, 0.75)",
  },
} satisfies ChartConfig

export function RevenueCustomerStatisticsChart({
  customerStatistics,
}: RevenueCustomerStatisticsChartProps) {
  const gradientId = useId().replace(/:/g, "")

  return (
    <Card className="gap-4 py-5">
      <CardHeader className="px-5 pb-0">
        <CardTitle className="text-sm font-semibold text-foreground">
          Customer Statistics
        </CardTitle>
        <p className="text-xs text-muted-foreground">
          Based on Amount generated by New and Returning Customers
        </p>
      </CardHeader>
      <CardContent className="px-2 pb-2 sm:px-4">
        <ChartContainer
          config={chartConfig}
          className="aspect-auto h-[320px] w-full"
        >
          <BarChart
            accessibilityLayer
            data={customerStatistics}
            margin={{ left: 8, right: 12, top: 8 }}
          >
            <defs>
              <linearGradient
                id={gradientId}
                x1="0"
                y1="0"
                x2="0"
                y2="1"
                gradientUnits="objectBoundingBox"
              >
                <stop offset="5.56%" stopColor="rgba(255, 181, 65, 0.95)" />
                <stop offset="100%" stopColor="rgba(255, 181, 65, 0.35)" />
              </linearGradient>
            </defs>
            <CartesianGrid vertical={false} strokeDasharray="4 4" />
            <YAxis
              width={48}
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) => formatCompactCount(Number(value))}
            />
            <XAxis
              dataKey="month"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
            />
            <ChartTooltip
              cursor={false}
              content={
                <ChartTooltipContent
                  formatter={(value, name) => [
                    formatCompactCount(Number(value)),
                    name === "returning_customers"
                      ? "Returning Customers"
                      : "New Customers",
                  ]}
                />
              }
            />
            <ChartLegend content={<ChartLegendContent />} />
            <Bar
              dataKey="returning_customers"
              fill="var(--color-returning_customers)"
              radius={[4, 4, 0, 0]}
              barSize={16}
            />
            <Bar
              dataKey="new_customers"
              fill={`url(#${gradientId})`}
              radius={[4, 4, 0, 0]}
              barSize={16}
            />
          </BarChart>
        </ChartContainer>
      </CardContent>
    </Card>
  )
}
