import type {
  SalesTransactionHistoryRow,
  SalesTransactionHistorySummary,
} from "../types"

export const SALES_TRANSACTION_HISTORY_SUMMARY: SalesTransactionHistorySummary =
  {
    totalTransactions: 22,
    totalTransactionsBadge: "",
    totalTransactionsSubtitle: "Across all dining channels",
    totalRevenue: 87_000,
    totalRevenueBadge: "",
    totalRevenueSubtitle: "Gross system revenue",
    averageOrderValue: 3_955,
    averageOrderValueBadge: "",
    averageOrderValueSubtitle: "Average value for selected period",
    refundedCount: 0,
    refundedAmount: 0,
    refundedBadge: "",
    refundedSubtitle: "0% of gross revenue",
  }

export const SALES_TRANSACTION_HISTORY_DATE_LABEL = "Aug 1 - Aug 19, 2025"

export const SALES_TRANSACTION_HISTORY_TOTAL = 847
export const SALES_TRANSACTION_HISTORY_PAGE_SIZE = 7
export const SALES_TRANSACTION_HISTORY_TOTAL_PAGES = 85

export const SALES_TRANSACTION_HISTORY_ROWS: SalesTransactionHistoryRow[] = [
  {
    id: "txn-h-0897",
    transactionNumber: "#TXN-0897",
    dateTimeLabel: "Aug 19, 2025 • 14:32",
    customerName: "Olamide Soyinka",
    source: "walk_in",
    sourceLabel: "Walk-in",
    itemsOrdered: "Jollof Rice & Chicken (x2), Suy...",
    amount: 9_500,
    paymentMethod: "Cash",
    staff: "Aisha B.",
    status: "completed",
    statusLabel: "Completed",
  },
  {
    id: "txn-h-0896",
    transactionNumber: "#TXN-0896",
    dateTimeLabel: "Aug 19, 2025 • 13:15",
    customerName: "Chidi Egwu",
    source: "whatsapp",
    sourceLabel: "WhatsApp",
    itemsOrdered: "Pepper Soup (x1), Plantain (x2)",
    amount: 2_800,
    paymentMethod: "Transfer",
    staff: "Web POS",
    status: "completed",
    statusLabel: "Completed",
  },
  {
    id: "txn-h-0895",
    transactionNumber: "#TXN-0895",
    dateTimeLabel: "Aug 19, 2025 • 12:48",
    customerName: "Ada Nwosu",
    source: "glovo",
    sourceLabel: "Glovo",
    itemsOrdered: "Party Jollof Tray",
    amount: 12_300,
    paymentMethod: "Card",
    staff: "Kemi L.",
    status: "completed",
    statusLabel: "Completed",
  },
  {
    id: "txn-h-0894",
    transactionNumber: "#TXN-0894",
    dateTimeLabel: "Aug 18, 2025 • 18:20",
    customerName: "Ibrahim Musa",
    source: "chowdeck",
    sourceLabel: "Chowdeck",
    itemsOrdered: "Beef Suya Wrap (x3)",
    amount: 4_100,
    paymentMethod: "Transfer",
    staff: "Web POS",
    status: "pending",
    statusLabel: "Pending",
  },
  {
    id: "txn-h-0893",
    transactionNumber: "#TXN-0893",
    dateTimeLabel: "Aug 18, 2025 • 17:05",
    customerName: "Grace Okon",
    source: "web",
    sourceLabel: "Web",
    itemsOrdered: "Combo Box A (x2)",
    amount: 6_750,
    paymentMethod: "Card",
    staff: "Web POS",
    status: "completed",
    statusLabel: "Completed",
  },
  {
    id: "txn-h-0892",
    transactionNumber: "#TXN-0892",
    dateTimeLabel: "Aug 17, 2025 • 11:30",
    customerName: "Tunde Ade",
    source: "walk_in",
    sourceLabel: "Walk-in",
    itemsOrdered: "Amala & Ewedu (x4)",
    amount: 11_000,
    paymentMethod: "Cash",
    staff: "Aisha B.",
    status: "completed",
    statusLabel: "Completed",
  },
  {
    id: "txn-h-0891",
    transactionNumber: "#TXN-0891",
    dateTimeLabel: "Aug 17, 2025 • 10:15",
    customerName: "Zainab Ali",
    source: "whatsapp",
    sourceLabel: "WhatsApp",
    itemsOrdered: "Fried Rice (x2)",
    amount: 5_600,
    paymentMethod: "Transfer",
    staff: "Web POS",
    status: "refunded",
    statusLabel: "Refunded",
  },
]
