"use client"

import type { ComponentType, SVGAttributes } from "react"
import {
  AlertTriangle,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  BookOpen,
  Calendar,
  Camera,
  CheckCircle2,
  Clock,
  Check,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  CircleHelp,
  ClipboardList,
  CreditCard,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  FileSpreadsheet,
  Filter,
  Flame,
  GripVertical,
  Headphones,
  Heart,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  List,
  Loader2,
  Lock,
  LogOut,
  Laptop,
  Mail,
  MapPin,
  MessageCircle,
  Menu,
  Minus,
  MonitorSmartphone,
  Moon,
  Music2,
  Package,
  PanelLeft,
  Pencil,
  Percent,
  Play,
  Plus,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Soup,
  Star,
  Store,
  Sun,
  Tag,
  Tags,
  Trash2,
  ThumbsUp,
  TrendingUp,
  Truck,
  Upload,
  UserCircle,
  UserCog,
  UserPlus,
  Users,
  UtensilsCrossed,
  Video,
  X,
  XCircle,
  type LucideIcon,
  type LucideProps,
} from "lucide-react"

export interface IconProps {
  size?: number
  className?: string
  color?: string
}

type IconComponent = ComponentType<IconProps & SVGAttributes<SVGSVGElement>>

function fromLucide(LucideIcon: LucideIcon): IconComponent {
  return function Icon({ size = 20, className, color, ...props }: IconProps & SVGAttributes<SVGSVGElement>) {
    const lucideProps: LucideProps = { size, className, ...props }
    if (color) lucideProps.color = color
    return <LucideIcon {...lucideProps} />
  }
}

export const Icons = {
  alert: fromLucide(AlertTriangle),
  account: fromLucide(UserCircle),
  add: fromLucide(Plus),
  arrowDownRight: fromLucide(ArrowDownRight),
  arrowForward: fromLucide(ArrowRight),
  arrowUp: fromLucide(ChevronUp),
  arrowUpRight: fromLucide(ArrowUpRight),
  banknote: fromLucide(Banknote),
  book: fromLucide(BookOpen),
  calendar: fromLucide(Calendar),

  camera: fromLucide(Camera),
  cart: fromLucide(ShoppingCart),
  check: fromLucide(Check),
  checkCircle2: fromLucide(CheckCircle2),
  clock: fromLucide(Clock),
  chevronDown: fromLucide(ChevronDown),
  chevronLeft: fromLucide(ChevronLeft),
  chevronRight: fromLucide(ChevronRight),
  circleHelp: fromLucide(CircleHelp),
  close: fromLucide(X),
  creditCard: fromLucide(CreditCard),
  download: fromLucide(Download),
  edit: fromLucide(Pencil),
  expandMore: fromLucide(ChevronDown),
  eye: fromLucide(Eye),
  eyeOff: fromLucide(EyeOff),
  facebook: fromLucide(Share2),
  favorite: fromLucide(Tags),
  favoriteFilled: fromLucide(Heart),
  fileText: fromLucide(FileText),
  fileSpreadsheet: fromLucide(FileSpreadsheet),
  filter: fromLucide(Filter),
  flame: fromLucide(Flame),
  gridView: fromLucide(LayoutGrid),
  group: fromLucide(Users),
  headphones: fromLucide(Headphones),
  heart: fromLucide(Heart),
  instagram: fromLucide(Camera),
  inventory: fromLucide(BarChart3),
  kitchen: fromLucide(ChefHat),
  landmark: fromLucide(Landmark),
  layers: fromLucide(Layers),
  list: fromLucide(List),

  listAlt: fromLucide(ClipboardList),
  link: fromLucide(Link2),
  laptop: fromLucide(Laptop),
  loader: fromLucide(Loader2),
  lock: fromLucide(Lock),
  logout: fromLucide(LogOut),
  mail: fromLucide(Mail),
  mapPin: fromLucide(MapPin),
  menu: fromLucide(Menu),
  messageCircle: fromLucide(MessageCircle),
  monitorSmartphone: fromLucide(MonitorSmartphone),
  moon: fromLucide(Moon),
  motopilot: fromLucide(Bike),
  moreHorizontal: fromLucide(Ellipsis),
  notifications: fromLucide(Bell),
  orders: fromLucide(ShoppingBag),
  panelLeft: fromLucide(PanelLeft),
  percent: fromLucide(Percent),
  performance: fromLucide(TrendingUp),
  priceTag: fromLucide(Tag),
  remove: fromLucide(Minus),
  revenue: fromLucide(CircleDollarSign),
  rotateCcw: fromLucide(RotateCcw),
  search: fromLucide(Search),
  send: fromLucide(Send),
  settings: fromLucide(Settings),
  shield: fromLucide(Shield),
  sparkles: fromLucide(Sparkles),
  soup: fromLucide(Soup),
  star: fromLucide(Star),
  store: fromLucide(Store),
  sun: fromLucide(Sun),
  thumbsUp: fromLucide(ThumbsUp),
  tiktok: fromLucide(Music2),
  trash: fromLucide(Trash2),
  truck: fromLucide(Truck),
  upload: fromLucide(Upload),
  userCog: fromLucide(UserCog),
  userPlus: fromLucide(UserPlus),
  utensilsCrossed: fromLucide(UtensilsCrossed),
  dashboard: fromLucide(LayoutDashboard),
  delivery: fromLucide(Package),
  dragIndicator: fromLucide(GripVertical),
  x: fromLucide(AtSign),
  xCircle: fromLucide(XCircle),
  youtube: fromLucide(Play),
  video: fromLucide(Video),
} as const

export type IconName = keyof typeof Icons

export function Icon({
  name,
  size = 20,
  className,
  color,
  ...props
}: { name: IconName } & IconProps & SVGAttributes<SVGSVGElement>) {
  const Component = Icons[name]
  return <Component size={size} className={className} color={color} {...props} />
}
